repo_url: https://github.com/dpmland/dpm
site_name: DPM Docs
site_url: https://nvim-lsp.github.io/
edit_uri: https://github.com/dpmland/docsland/edit/main/docs


theme:
  name: material
  logo: assets/logo.png
  favicon: assets/images/favicon.ico
  palette:

  - media: '(prefers-color-scheme: light)'
    accent: blue
    primary: blue
    scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode

  - media: '(prefers-color-scheme: dark)'
    accent: blue
    primary: blue
    scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode

    features:
    - navigation.expand
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top
markdown_extensions:
- pymdownx.highlight
- pymdownx.superfences
- pymdownx.magiclink
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  social:
  - icon: fontawesome/brands/discord
    link: https://dpmland.deno.dev/discord
  - icon: fontawesome/brands/github
    link: https://github.com/dpmland/dpm
  - icon: fontawesome/brands/twitter
    link: https://twitter.com
  - icon: material/home
    link: https://dpmland.deno.dev
extra_css:
  - assets/extra.css

nav:
  - Home: index.md
  - Install: installation.md
  - Commands:
    - commands/index.md
    - '... | commands/*.md'
  - '...'
plugins:
  - search
  - awesome-pages
