name: FMT Check

on:
  push:
    branches: [main]

jobs:
  publish:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@master

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 1.24.3

      - name: Check the formatting rules
        run: deno task fmt:check
        env:
          NO_COLOR: true
