name: Publish docs via GitHub Pages

on:
  push:
    branches: [main]

jobs:
  publish:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@master

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 1.24.3

      - name: Check the formatting rules
        run: deno task fmt:check
        env:
          NO_COLOR: true

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REQUIREMENTS: requirements.txt
